# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  combat_log:
    build: ./
    container_name: combat_log
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
